apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: osm-ingress
  namespace: bookstore
  annotations:
    kubernetes.io/ingress.class: nginx    
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  # tls:
  # - hosts:
  #   - store.wkshpdev.com
  #   secretName: osm-tls-secret
  rules:
  - host: store.<dns-name>
    http:
      paths:
      - path: /store
        pathType: Prefix
        backend:
          service:
            name: bookstore
            port:
              number: 14001

---
kind: IngressBackend
apiVersion: policy.openservicemesh.io/v1alpha1
metadata:
  name: bookstore-backend
  namespace: bookstore
spec:
  backends:
  - name: bookstore
    port:
      number: 14001
      protocol: http
  sources:
  - kind: Service
    namespace: osm-nginx-ingess-ns
    name: osm-nginx-ingess-ingress-nginx-controller