apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: emojivoto-split
  namespace: emojivoto
spec:  
  service: web-svc
  backends:
  - service: web-svc
    weight: 100
  
#UNCOMMENT: Test Traffic Shifting
  # - service: web-svc-v12
  #   weight: 0