ingress:
  name: aks-workshop-ingress
  namespace: aks-workshop-qa
  annotations:
    ingressClass: nginx
    proxyBodySize: "10m"
    enableCors: "true"
    rewriteTarget: /$1
    serviceUpstream: "true"
    configurationSnippet:
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
  hosts:
  - name: qa.internal.wkshpdev.com
    paths:
    - path: /?(.*)
      pathType: ImplementationSpecific
      service: ratingsweb-service
      port: 81