ingress:
  name: service-mesh-ingress
  # namespace: aks-workshop-dev
  annotations:
    ingressClass: nginx
    proxyBodySize: "10m"
    enableCors: "true"
    rewriteTarget: /$1
    serviceUpstream: "true"
    configurationSnippet:
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
  hosts:
  - name: 40.76.135.1.nip.io
    paths:    
    - path: /?(.*)
      pathType: Prefix
      service: ratingsweb-service
      port: 80    