apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratingsfault-virtual-service
spec:
  hosts:
  - ratings
  http:
  - fault:
      delay:
        percentage:
          value: 50.0
        fixedDelay: 7s    
    route:
    - destination:
        host: ratings
        subset: v1
