apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: frontend-split
  namespace: test
spec:  
  service: frontend-blue
  backends:
  - service: frontend-blue    
    weight: 100

#UNCOMMENT: Test Blue/Green
  # - service: frontend-green
  #   weight: 0